const triangle = {
    content: "",
    position: "absolute",
    borderStyle: "solid",
    display: "block",
    width: "0",
    zIndex: "1",
    top: "7px",
}

export default {
    container: {
        width: "calc(100vw - 460px)",
        marginLeft: "300px",
        minWidth: "400px",
        position: "absolute",
        top: "40px",
        height: "calc(100% - 40px)",
    },
    messagesDiv: {
        maxWidth: "700px",
        width: "95%",
        minWidth: "380px",
        height: "calc(100% - 62px)",
        minHeight: "250px",
        margin: "0 auto",
        zIndex: "-1",
        overflow: "auto",
        borderLeft: "2px solid #cccccc",
        borderRight: "2px solid #ffc547",
        WebkitOverflowScrolling: "touch",
    },
    inputDiv: {
        position: "relative",
        maxWidth: "700px",
        width: "95%",
        minWidth: "380px",
        margin: "9px auto",
        zIndex: "80",
        overflow: "hidden",
    },
    inputTextArea: {
        width: "85%",
        verticalAlign: "top",
        padding: "5px",
        resize: "none",
        border: "none",
        overflow: "hidden",
        height: "30px",
        marginLeft: "8px",
        borderRadius: "5px",
        maxHeight: "260px",
        fontWeight: "bolder", // finally
        ":focus": {
            border: "1px solid #ffb524",
        },
    },
    sendButton: {
        backgroundColor: "#ffc547",
        border: "none",
        height: "30px",
        width: "12%",
        fontSize: "18px",
        borderRadius: "5px",
        marginLeft: "3px",
        ":hover": {
            backgroundColor: "orange",
        },
    },
}

export const chatItem = {
    bubbleWrapper: {
        display: "block",
        width: "100%",
        minHeight: "40px",
        overflow: "hidden",
    },
    otherBubble: {
        backgroundColor: "#cccccc",
        color: "black",
        maxWidth: "calc(100% - 100px)",
        float: "left",
        display: "block",
        margin: "10px",
        padding: "4px 10px 4px 10px",
        fontSize: "20px",
        borderRadius: "5px",
        minHeight: "40px",
        position: "relative",
        wordWrap: "break-word",
        verticalAlign: "middle",
    },
    selfBubble: {
        backgroundColor: "#ffc547",
        color: "black",
        maxWidth: "calc(100% - 100px)",
        float: "right",
        display: "block",
        margin: "10px",
        padding: "4px 10px 4px 10px",
        fontSize: "20px",
        borderRadius: "5px",
        minHeight: "40px",
        position: "relative",
        wordWrap: "break-word",
    },
    otherTriangle: [triangle, {
        borderColor: "transparent #cccccc",
        left: "-9px",
        borderWidth: "6px 9px 6px 0px",
    }],
    selfTriangle: [triangle, {
        borderColor: "transparent #ffc547",
        right: "-9px",
        borderWidth: "6px 0px 6px 9px",
    }],
    profPic: {
        width: "30px",
        height: "30px",
        objectFit: "cover",
        borderRadius: "5px",
        marginTop: "-5px",
    },
    chatOpponent: {
        display: "inline-block",
        paddingRight: "5px",
        fontWeight: "400",
        marginBottom: "0",
        marginLeft: "8px",
        cursor: "pointer",
        ":hover": {
            borderBottom: "1px solid #777",
        },
    },
}
